# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab4fa968d90bb9b5292140f42f28e0c4051f5b876f725c32ac3a94f16794e9b462939e335dd44fd97837ddcaf702a4372c0d0cc54d20c62871f13150ee49fc33

test:
  secret_key_base: 07e68f16b80e5fd615c981eb147e227ec221ca4d03d312632c09136d485fa69aaf03c7934b2393ea3bb92e1eda2d43873412d0d63f129dc2aef66add293db5c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
